language: php
php:
  - '8.1'

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - ./phpunit

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: james@jgrundner.com
