language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - ./phpunit

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: james@jgrundner.com
